### PR TITLE
Add Japanese

### PR DESCRIPTION
**Pull request by u7f8au7fbd**

### CODE REVIEW

**Review by oierbravo — CHANGES_REQUESTED** [review]
Hi!
Can you plz put the translation file in `src/main/resources/assets/create-mechanical-extruder/lang/ja_jp.json`
It's the correct place :)

**Comment by u7f8au7fbd** [comment]
Sorry. I was mistaken. I will correct it later.

**Comment by u7f8au7fbd** [comment]
I made the change.

**Comment by oierbravo** [comment]
Perfect! thx!

**Pull request merged**
